#========================================MYSQL================================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
#=============================================================================================

#============= OAuth2 config ====================
oauth2:
  client-id: clientIdPassword
  client-secret: 123
  grand-types: password,refresh_token,authorization_code
  scopes: read
  access-token-expire-in: 3600
  refresh-token-expire-in: 7200

#=========== Java Key Store config ===============
key:
  file-name: kt3key.jks
  file-password: hdkey@
  alias: oauth2
  alias-password: hdkt3!

#=========== Application config ===================
server:
  port: 8181
application:
  title: Travel Service
  version: 1.0.0
